name: "Container Security Scan"

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  container-security-scan:
    runs-on: ubuntu-latest
    name: Scan Container Image for Vulnerabilities
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          docker build -t juice-shop:latest .
      
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'juice-shop:latest'
          format: 'json'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: 'trivy-report.json'
      
      - name: Upload Trivy JSON Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results-json
          path: trivy-report.json
  