name: "DAST with OWASP ZAP"

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  dast:
    name: DAST - OWASP ZAP Scan
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for Juice Shop to be ready
        run: |
          for i in {1..30}; do
            curl -sSf http://localhost:3000 && break
            sleep 5
          done

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --network=host \
            -v $(pwd):/zap/wrk/:rw \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:3000 \
            -r zap-report.html \
            -J zap-report.json \
            -w zap-report.md \
            -a || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-zap-report
          path: |
            zap-report.html
            zap-report.json
            zap-report.md
          if-no-files-found: warn
